[package]
name = "cytoscnpy-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cytoscnpy = { path = "../cytoscnpy" } # use library crate
anyhow = "1.0"

# Inherit lints from workspace
[lints]
workspace = true
