[package]
name = "cytoscnpy-cli"
version = "1.0.1"
edition = "2021"
license = "Apache-2.0"

[dependencies]
cytoscnpy = { path = "../cytoscnpy" } # use library crate
anyhow = "1.0"

# Inherit lints from workspace
[lints]
workspace = true
