name: Lint

on:
  pull_request:
    branches: ["main"]

jobs:
  prek:
    name: Prek Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Mold Linker
        uses: rui314/setup-mold@v1
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - uses: j178/prek-action@v1
      - name: Sync dependencies
        run: uv sync --extra dev
      - name: Type check with ty
        run: uvx ty check --output-format=github
