name: Lint

on:
  pull_request:
    branches: ["main"]

jobs:
  prek:
    name: Prek Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Mold Linker
        uses: rui314/setup-mold@v1
      - uses: j178/prek-action@v1
